[package]
name = "chal13"
version = "0.1.0"
authors = ["Philip Munksgaard <pmunksgaard@gmail.com>"]

[dependencies]
raes = { git = "https://github.com/Munksgaard/raes" }
pkcs7pad = { git = "https://github.com/Munksgaard/pkcs7pad" }
