[package]
name = "chal3"
version = "0.1.0"
authors = ["Philip Munksgaard <pmunksgaard@gmail.com>"]

[dependencies]
hexstr = { git = "https://github.com/Munksgaard/hexstr" }
freqalyze = { git = "https://github.com/Munksgaard/freqalyze" }
