[package]
name = "chal10"
version = "0.1.0"
authors = ["Philip Munksgaard <pmunksgaard@gmail.com>"]

[dependencies]
raes = { git = "https://github.com/Munksgaard/raes" }
base64 = { git = "https://github.com/Munksgaard/base64" }
